import { useEffect, useRef, useState } from "react";
import { Captions, Cpu, Download, Gauge, Palette, ScanSearch, Scissors, Upload, WandSparkles } from "lucide-react";
import { analyzeMotion, detectMediaCapabilities, generateProxy, pickLutFile, pickTranscriptionModel, transcribeLocal, type MediaCapabilities } from "../lib/native";
import { parseCaptionFile, serializeSrt, serializeVtt } from "../lib/captions";
import { defaultCaptionStyle, formatTime, id, SECOND } from "../lib/project";
import type { Caption, OpenFrameProject, SpeedPoint, TimelineItem } from "../types/project";

export function AdvancedToolPanel({ tool, project, item, playheadUs, onProject, onItem, onStatus }: { tool: string; project: OpenFrameProject; item?: TimelineItem; playheadUs: number; onProject: (project: OpenFrameProject) => void; onItem: (item: TimelineItem) => void; onStatus: (status: string) => void }) {
  if (tool === "captions") return <CaptionPanel project={project} item={item} playheadUs={playheadUs} onProject={onProject} onStatus={onStatus} />;
  if (!item) return <div className="panel-empty advanced-empty"><ScanSearch size={30} /><strong>Select a video clip</strong><small>Advanced cutout, tracking, speed, color, and proxy controls are clip-specific.</small></div>;
  return tool === "cutout" ? <CutoutPanel item={item} onItem={onItem} /> : <PerformancePanel project={project} item={item} playheadUs={playheadUs} onProject={onProject} onItem={onItem} onStatus={onStatus} />;
}

function CaptionPanel({ project, item, playheadUs, onProject, onStatus }: { project: OpenFrameProject; item?: TimelineItem; playheadUs: number; onProject: (project: OpenFrameProject) => void; onStatus: (status: string) => void }) {
  const input = useRef<HTMLInputElement>(null);
  const update = (captions: Caption[]) => onProject({ ...project, sequence: { ...project.sequence, captions } });
  const add = () => update([...project.sequence.captions, { id: id("caption"), startUs: playheadUs, endUs: playheadUs + 2 * SECOND, text: "New caption", words: [], style: defaultCaptionStyle() }]);
  const importFile = async (file?: File) => { if (!file) return; const captions = parseCaptionFile(await file.text()); update([...project.sequence.captions, ...captions]); onStatus(`Imported ${captions.length} captions`); };
  const download = (format: "srt" | "vtt") => { const content = format === "srt" ? serializeSrt(project.sequence.captions) : serializeVtt(project.sequence.captions); const url = URL.createObjectURL(new Blob([content], { type: "text/plain" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${project.name}.${format}`; anchor.click(); URL.revokeObjectURL(url); };
  const asset = project.assets.find((value) => value.id === item?.assetId);
  const chooseModel = async () => { const transcriptionModelPath = await pickTranscriptionModel(); if (transcriptionModelPath) onProject({ ...project, settings: { ...project.settings, transcriptionModelPath } }); };
  const transcribe = async () => { if (!asset) { onStatus("Select a video or audio clip to transcribe"); return; } let transcriptionModelPath = project.settings.transcriptionModelPath; if (!transcriptionModelPath) transcriptionModelPath = await pickTranscriptionModel(); if (!transcriptionModelPath) return; onStatus("Transcribing locally…"); try { const captions = parseCaptionFile(await transcribeLocal(asset.path, transcriptionModelPath)); onProject({ ...project, settings: { ...project.settings, transcriptionModelPath }, sequence: { ...project.sequence, captions: [...project.sequence.captions, ...captions] } }); onStatus("Local transcription added " + captions.length + " captions"); } catch (error) { onStatus("Local transcription failed: " + error); } };  return <div className="advanced-panel"><div className="panel-heading"><div><span className="eyebrow">TEXT ENGINE</span><h2>Captions</h2></div></div><div className="advanced-actions"><button onClick={add}>+ Manual</button><button onClick={() => input.current?.click()}><Upload size={12} /> Import</button><button onClick={() => download("srt")}><Download size={12} /> SRT</button><button onClick={() => download("vtt")}><Download size={12} /> VTT</button></div><input ref={input} hidden type="file" accept=".srt,.vtt,text/plain" onChange={(event) => void importFile(event.target.files?.[0])} />
    <div className="caption-list">{project.sequence.captions.map((caption) => <article key={caption.id} className="caption-card"><textarea aria-label="Caption text" value={caption.text} onChange={(event) => update(project.sequence.captions.map((value) => value.id === caption.id ? { ...value, text: event.target.value } : value))} /><div className="property-grid"><label>Start (s)<input aria-label="Caption start" type="number" step=".1" value={(caption.startUs / SECOND).toFixed(1)} onChange={(event) => update(project.sequence.captions.map((value) => value.id === caption.id ? { ...value, startUs: Math.round(Number(event.target.value) * SECOND) } : value))} /></label><label>End (s)<input aria-label="Caption end" type="number" step=".1" value={(caption.endUs / SECOND).toFixed(1)} onChange={(event) => update(project.sequence.captions.map((value) => value.id === caption.id ? { ...value, endUs: Math.round(Number(event.target.value) * SECOND) } : value))} /></label></div><div className="caption-style-row"><input aria-label="Caption color" type="color" value={caption.style.color} onChange={(event) => updateStyle(project, caption.id, { color: event.target.value }, update)} /><input aria-label="Caption background" type="color" value={caption.style.backgroundColor} onChange={(event) => updateStyle(project, caption.id, { backgroundColor: event.target.value }, update)} /><input aria-label="Caption size" type="number" min="8" max="300" value={caption.style.fontSize} onChange={(event) => updateStyle(project, caption.id, { fontSize: Number(event.target.value) }, update)} /><button aria-label="Delete caption" onClick={() => update(project.sequence.captions.filter((value) => value.id !== caption.id))}>×</button></div></article>)}</div>
    <div className="model-status"><Cpu size={14} /><span>Local transcription adapter</span><b>{project.settings.transcriptionModelPath ? "Model configured" : "Model not installed"}</b><small>Runs entirely on-device with a compatible whisper.cpp model and CLI placed together.</small></div>
    <div className="advanced-actions"><button onClick={() => void chooseModel()}><Cpu size={12} /> Choose model</button><button disabled={!asset} onClick={() => void transcribe()}><Captions size={12} /> Auto captions</button></div>
  </div>;
}

function CutoutPanel({ item, onItem }: { item: TimelineItem; onItem: (item: TimelineItem) => void }) {
  const chroma = item.chromaKey, auto = item.autoBackground;
  return <div className="advanced-panel"><div className="panel-heading"><div><span className="eyebrow">LOCAL CUTOUT</span><h2>Background</h2></div></div><section><h3><WandSparkles size={14} /> Chroma key</h3><label className="check-label"><input aria-label="Enable chroma key" type="checkbox" checked={chroma.enabled} onChange={(event) => onItem({ ...item, chromaKey: { ...chroma, enabled: event.target.checked } })} /> Enable green-screen removal</label><label className="color-label">Key color<input aria-label="Key color" type="color" value={chroma.keyColor} onChange={(event) => onItem({ ...item, chromaKey: { ...chroma, keyColor: event.target.value } })} /></label>{(["tolerance", "softness", "spill", "opacity"] as const).map((key) => <label className="slider-label" key={key}><span>{key} <b>{Math.round(chroma[key] * 100)}%</b></span><input aria-label={`Chroma ${key}`} type="range" min="0" max="1" step=".01" value={chroma[key]} onChange={(event) => onItem({ ...item, chromaKey: { ...chroma, [key]: Number(event.target.value) } })} /></label>)}<label className="check-label"><input aria-label="Show chroma mask" type="checkbox" checked={chroma.showMask} onChange={(event) => onItem({ ...item, chromaKey: { ...chroma, showMask: event.target.checked } })} /> Show mask</label><label className="check-label"><input aria-label="Invert chroma key" type="checkbox" checked={chroma.inverted} onChange={(event) => onItem({ ...item, chromaKey: { ...chroma, inverted: event.target.checked } })} /> Invert</label></section>
    <section><h3>Automatic background removal</h3><label className="check-label"><input aria-label="Enable automatic background removal" type="checkbox" checked={auto.enabled} onChange={(event) => onItem({ ...item, autoBackground: { ...auto, enabled: event.target.checked } })} /> Fast local sampled-color cutout</label><label className="color-label">Background sample<input aria-label="Background sample" type="color" value={auto.sampledColor} onChange={(event) => onItem({ ...item, autoBackground: { ...auto, sampledColor: event.target.value } })} /></label><label className="slider-label"><span>Refinement <b>{Math.round(auto.refinement * 100)}%</b></span><input aria-label="Background refinement" type="range" min="0" max="1" step=".01" value={auto.refinement} onChange={(event) => onItem({ ...item, autoBackground: { ...auto, refinement: Number(event.target.value) } })} /></label><div className="model-status"><Cpu size={14} /><span>Semantic person segmentation</span><b>Optional model not installed</b><small>The fast local mode is available now. Semantic background removal remains disabled until a compatible licensed local model is configured.</small></div></section>
  </div>;
}

function PerformancePanel({ project, item, playheadUs, onProject, onItem, onStatus }: { project: OpenFrameProject; item: TimelineItem; playheadUs: number; onProject: (project: OpenFrameProject) => void; onItem: (item: TimelineItem) => void; onStatus: (status: string) => void }) {
  const [capabilities, setCapabilities] = useState<MediaCapabilities>(); useEffect(() => { void detectMediaCapabilities().then(setCapabilities); }, []);
  const asset = project.assets.find((value) => value.id === item.assetId); const localUs = Math.max(0, Math.min(item.durationUs, playheadUs - item.startUs));
  const addSpeed = () => { const point: SpeedPoint = { id: id("speed"), timeUs: localUs, rate: item.playbackRate, easing: "ease-in-out" }; onItem({ ...item, speedPoints: [...item.speedPoints.filter((value) => Math.abs(value.timeUs - localUs) > 10_000), point].sort((a, b) => a.timeUs - b.timeUs) }); };
  const runProxy = async () => { if (!asset) return; onStatus("Generating proxy…"); try { const proxyPath = await generateProxy(asset.path); onProject({ ...project, assets: project.assets.map((value) => value.id === asset.id ? { ...value, proxyPath, proxyEnabled: true, proxyStatus: "ready" } : value) }); onStatus("Proxy ready"); } catch (error) { onStatus(`Proxy failed: ${error}`); } };
  const runTracking = async () => { if (!asset) return; onStatus("Analyzing motion…"); try { const points = await analyzeMotion(asset.path); onItem({ ...item, motionTracking: { ...item.motionTracking, points, analyzed: true } }); onStatus(`Motion analysis created ${points.length} points`); } catch (error) { onStatus(`Motion analysis failed: ${error}`); } };
  return <div className="advanced-panel"><div className="panel-heading"><div><span className="eyebrow">ADVANCED VIDEO</span><h2>Performance</h2></div></div><section><h3><Gauge size={14} /> Speed ramp</h3><button className="wide-action" onClick={addSpeed}>Add speed point at {formatTime(localUs)}</button>{item.speedPoints.map((point) => <div className="speed-row" key={point.id}><code>{formatTime(point.timeUs)}</code><input aria-label="Speed point rate" type="number" min=".25" max="4" step=".05" value={point.rate} onChange={(event) => onItem({ ...item, speedPoints: item.speedPoints.map((value) => value.id === point.id ? { ...value, rate: Number(event.target.value) } : value) })} /><select value={point.easing} onChange={(event) => onItem({ ...item, speedPoints: item.speedPoints.map((value) => value.id === point.id ? { ...value, easing: event.target.value as SpeedPoint["easing"] } : value) })}><option value="linear">Linear</option><option value="ease-in">Ease in</option><option value="ease-out">Ease out</option><option value="ease-in-out">Ease both</option></select><button onClick={() => onItem({ ...item, speedPoints: item.speedPoints.filter((value) => value.id !== point.id) })}>×</button></div>)}</section>
    <section><h3><Palette size={14} /> Advanced color</h3>{(["exposure", "vibrance", "temperature", "tint", "highlights", "shadows", "whites", "blacks", "fade"] as const).map((key) => <label className="slider-label" key={key}><span>{key} <b>{item.advancedColor[key].toFixed(2)}</b></span><input aria-label={`Advanced ${key}`} type="range" min={key === "exposure" ? -5 : -1} max={key === "exposure" ? 5 : 1} step=".01" value={item.advancedColor[key]} onChange={(event) => onItem({ ...item, advancedColor: { ...item.advancedColor, [key]: Number(event.target.value) } })} /></label>)}<div className="lut-row"><button onClick={async () => { const lutPath = await pickLutFile(); if (lutPath) onItem({ ...item, lutPath }); }}>Choose LUT</button><span title={item.lutPath}>{item.lutPath?.split(/[\\/]/).at(-1) ?? "None"}</span><input aria-label="LUT intensity" type="range" min="0" max="1" step=".01" value={item.lutIntensity} onChange={(event) => onItem({ ...item, lutIntensity: Number(event.target.value) })} /></div></section>
    <section><h3>Stabilization & tracking</h3><label className="check-label"><input aria-label="Enable stabilization" type="checkbox" checked={item.stabilization.enabled} onChange={(event) => onItem({ ...item, stabilization: { ...item.stabilization, enabled: event.target.checked } })} /> Stabilize locally</label><label className="slider-label"><span>Strength <b>{Math.round(item.stabilization.strength * 100)}%</b></span><input aria-label="Stabilization strength" type="range" min="0" max="1" step=".01" value={item.stabilization.strength} onChange={(event) => onItem({ ...item, stabilization: { ...item.stabilization, strength: Number(event.target.value) } })} /></label><button className="wide-action" onClick={() => void runTracking()}><ScanSearch size={13} /> Analyze motion forward</button>{item.motionTracking.analyzed && <small>{item.motionTracking.points.length} tracking points cached in the project.</small>}</section>
    <section><h3>Proxy & acceleration</h3><button className="wide-action" onClick={() => void runProxy()}><Scissors size={13} /> {asset?.proxyStatus === "ready" ? "Regenerate proxy" : "Generate 960px proxy"}</button>{asset?.proxyStatus === "ready" && <label className="check-label"><input aria-label="Use proxy" type="checkbox" checked={asset.proxyEnabled} onChange={(event) => onProject({ ...project, assets: project.assets.map((value) => value.id === asset.id ? { ...value, proxyEnabled: event.target.checked } : value) })} /> Use proxy for preview</label>}<label className="select-label">Preview quality<select aria-label="Preview quality" value={project.settings.previewQuality} onChange={(event) => onProject({ ...project, settings: { ...project.settings, previewQuality: event.target.value as OpenFrameProject["settings"]["previewQuality"] } })}><option value="full">Full</option><option value="half">1/2</option><option value="quarter">1/4</option><option value="proxy">Proxy</option></select></label><label className="select-label">Export encoder<select aria-label="Hardware encoder" value={project.settings.hardwareEncoder} onChange={(event) => onProject({ ...project, settings: { ...project.settings, hardwareEncoder: event.target.value as OpenFrameProject["settings"]["hardwareEncoder"] } })}><option value="software">Software H.264</option>{capabilities?.hardwareEncoders.map((encoder) => <option key={encoder} value={encoder}>{encoder}</option>)}</select></label><small>{capabilities ? `${capabilities.filters.length} advanced filters · ${capabilities.hardwareEncoders.length} hardware backends detected` : "Detecting local capabilities…"}</small></section>
  </div>;
}
function updateStyle(project: OpenFrameProject, id: string, patch: Partial<Caption["style"]>, update: (captions: Caption[]) => void) { update(project.sequence.captions.map((caption) => caption.id === id ? { ...caption, style: { ...caption.style, ...patch } } : caption)); }