import { useEffect, useMemo, useState } from "react";
import { Boxes, CheckCircle2, Download, ExternalLink, FileJson, FolderOpen, Info, PackagePlus, Palette, Plug, RefreshCw, ShieldCheck, Trash2, X } from "lucide-react";
import { applyPluginTheme, restorePluginTheme, setPluginSnapshot } from "../lib/plugins";
import { checkForUpdates, diagnosticsStatus, downloadPluginModel, exportDiagnostics, getPluginStatus, openLogsFolder, openPluginSource, openPluginsFolder, pickAndInstallPlugin, removePlugin, setPluginEnabled, type DiagnosticsStatus } from "../lib/native";
import type { PluginStatus } from "../types/plugins";

export function EcosystemCenter({ onClose }: { onClose: () => void }) {
  const [tab, setTab] = useState<"plugins" | "themes" | "models" | "about">("plugins");
  const [status, setStatus] = useState<PluginStatus>();
  const [diagnostics, setDiagnostics] = useState<DiagnosticsStatus>();
  const [busy, setBusy] = useState<string>();
  const [message, setMessage] = useState("Community packages stay local and are inspected before installation.");
  const enabled = status?.plugins.filter((plugin) => plugin.enabled) ?? [];
  const themes = enabled.flatMap((plugin) => plugin.package.contributions.themes.map((theme) => ({ plugin, theme })));
  const models = enabled.flatMap((plugin) => plugin.package.contributions.aiModels.map((model) => ({ plugin, model })));
  const totals = useMemo(() => status?.plugins.reduce((result, plugin) => {
    result.effects += plugin.package.contributions.effects.length;
    result.transitions += plugin.package.contributions.transitions.length;
    result.templates += plugin.package.contributions.templates.length;
    result.exporters += plugin.package.contributions.exporters.length;
    return result;
  }, { effects: 0, transitions: 0, templates: 0, exporters: 0 }), [status]);
  async function refresh() {
    const next = await getPluginStatus();
    setStatus(next); setPluginSnapshot(next); restorePluginTheme(next);
    setDiagnostics(await diagnosticsStatus());
  }
  useEffect(() => { void refresh().catch((error) => setMessage(String(error))); }, []);
  async function install() { setBusy("install"); try { const plugin = await pickAndInstallPlugin(); if (plugin) { await refresh(); setMessage(`Installed ${plugin.package.manifest.name}. Review permissions before enabling community content.`); } } catch (error) { setMessage("Plugin rejected: " + error); } finally { setBusy(undefined); } }
  async function toggle(pluginId: string, value: boolean) { setBusy(pluginId); try { await setPluginEnabled(pluginId, value); await refresh(); setMessage(value ? "Plugin enabled." : "Plugin disabled."); } catch (error) { setMessage("Could not change plugin: " + error); } finally { setBusy(undefined); } }
  async function uninstall(pluginId: string) { setBusy(pluginId); try { await removePlugin(pluginId); await refresh(); setMessage("Plugin removed."); } catch (error) { setMessage("Could not remove plugin: " + error); } finally { setBusy(undefined); } }
  async function downloadModel(pluginId: string, modelId: string) { const key = pluginId + ":" + modelId; setBusy(key); try { const path = await downloadPluginModel(pluginId, modelId); setMessage("Extension model verified and installed at " + path); } catch (error) { setMessage("Model installation failed: " + error); } finally { setBusy(undefined); } }

  return <div className="ecosystem-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <section className="ecosystem-center" role="dialog" aria-modal="true" aria-labelledby="ecosystem-title">
      <header><div><span className="eyebrow">OPEN ECOSYSTEM</span><h2 id="ecosystem-title">Extensions & diagnostics</h2><p>Safe local plugins, themes, community presets, model extensions, exporter presets, logs, and build information.</p></div><button className="icon-button" aria-label="Close ecosystem center" onClick={onClose}><X size={18}/></button></header>
      <nav>{([["plugins",<Plug/>,"Plugins"],["themes",<Palette/>,"Themes"],["models",<Boxes/>,"AI extensions"],["about",<Info/>,"About"]] as const).map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{icon}<span>{label}</span></button>)}</nav>
      <main>
        {tab==="plugins"&&<><div className="ecosystem-toolbar"><div><strong>Declarative Plugin SDK v1</strong><small>{status?.securitySummary}</small></div><button onClick={()=>void openPluginsFolder()}><FolderOpen size={13}/> Folder</button><button className="primary" disabled={busy==="install"} onClick={()=>void install()}><PackagePlus size={13}/> Install .of-plugin</button></div><div className="ecosystem-summary">{Object.entries(totals??{}).map(([key,value])=><span key={key}><b>{value}</b>{key}</span>)}</div><div className="plugin-list">{status?.plugins.map(({package:plugin,enabled,packageSha256})=><article key={plugin.manifest.id}><div className="plugin-icon"><Plug/></div><div className="plugin-copy"><span>{plugin.manifest.author} · {plugin.manifest.license}</span><h3>{plugin.manifest.name} <small>v{plugin.manifest.version}</small></h3><p>{plugin.manifest.description}</p><code>SHA-256 {packageSha256.slice(0,16)}…</code><div className="capability-chips">{plugin.manifest.permissions.map(value=><i key={"permission:"+value}>permission: {value}</i>)}{plugin.manifest.capabilities.map(value=><i key={value}>{value}</i>)}</div></div><div className="plugin-actions"><label><input type="checkbox" checked={enabled} disabled={busy===plugin.manifest.id} onChange={event=>void toggle(plugin.manifest.id,event.target.checked)}/>{enabled?"Enabled":"Disabled"}</label><button aria-label={"Remove "+plugin.manifest.name} onClick={()=>void uninstall(plugin.manifest.id)}><Trash2 size={13}/></button>{plugin.manifest.sourceUrl&&<button aria-label={"Source for "+plugin.manifest.name} onClick={()=>void openPluginSource(plugin.manifest.id)}><ExternalLink size={13}/></button>}</div></article>) ?? <p>Reading plugins…</p>}{status&&!status.plugins.length&&<div className="ecosystem-empty"><Plug/><strong>No plugins installed</strong><small>Create one from the documented SDK example or install a local .of-plugin file.</small></div>}</div></>}
        {tab==="themes"&&<><div className="ecosystem-toolbar"><div><strong>Community themes</strong><small>Only validated OpenFrame color tokens can change.</small></div><button onClick={()=>{applyPluginTheme();setMessage("Default theme restored.")}}>Use default</button></div><div className="theme-grid">{themes.map(({plugin,theme})=><button key={plugin.package.manifest.id+theme.id} onClick={()=>{applyPluginTheme(theme,plugin.package.manifest.id+":"+theme.id);setMessage("Applied "+theme.name)}}><span>{Object.values(theme.tokens).slice(0,6).map((color,index)=><i key={index} style={{background:color}}/>)}</span><strong>{theme.name}</strong><small>{plugin.package.manifest.name}</small></button>)}</div>{!themes.length&&<div className="ecosystem-empty"><Palette/><strong>No community themes</strong><small>Installed theme contributions will appear here.</small></div>}</>}
        {tab==="models"&&<><div className="model-security"><ShieldCheck/><span><strong>Explicit verified downloads</strong><small>Extension models require HTTPS, a declared license and size, and a 64-character SHA-256. Downloads start only after you click.</small></span></div><div className="extension-model-grid">{models.map(({plugin,model})=><article key={plugin.package.manifest.id+model.id}><Boxes/><span>{model.runtime}</span><h3>{model.name}</h3><p>{model.purpose}</p><dl><div><dt>Size</dt><dd>{formatBytes(model.sizeBytes)}</dd></div><div><dt>License</dt><dd>{model.license}</dd></div><div><dt>Version</dt><dd>{model.version}</dd></div></dl><code>{model.sha256.slice(0,16)}…</code><button disabled={busy===plugin.package.manifest.id+":"+model.id} onClick={()=>void downloadModel(plugin.package.manifest.id,model.id)}><Download size={13}/> Download & verify</button></article>)}</div>{!models.length&&<div className="ecosystem-empty"><Boxes/><strong>No AI model extensions</strong><small>Installed model contributions will appear here without replacing the official caption models.</small></div>}</>}
        {tab==="about"&&<><div className="about-card"><div className="about-mark">OF</div><div><span className="eyebrow">OPENFRAME</span><h3>Version {diagnostics?.appVersion??"…"}</h3><p>The free, open-source, local-first creative studio.</p></div></div><div className="diagnostics-grid"><span><small>Build</small><b>{diagnostics?.buildProfile}</b></span><span><small>Target</small><b>{diagnostics?.target}</b></span><span><small>FFmpeg</small><b>{diagnostics?.ffmpegAvailable?"Ready":"Missing"}</b></span><span><small>FFprobe</small><b>{diagnostics?.ffprobeAvailable?"Ready":"Missing"}</b></span><span><small>Plugins</small><b>{diagnostics?.installedPlugins??0}</b></span><span><small>Model files</small><b>{diagnostics?.installedModelFiles??0}</b></span></div><section className="update-card"><RefreshCw/><div><strong>Transparent updates</strong><p>{diagnostics?.updateMessage}</p></div><button onClick={async()=>{const next=await checkForUpdates();setDiagnostics(next);setMessage(next.updateMessage)}}>Check now</button></section><div className="about-actions"><button onClick={()=>void openLogsFolder()}><FolderOpen size={13}/> Open logs</button><button onClick={async()=>{const path=await exportDiagnostics();setMessage(path?"Diagnostics exported to "+path:"Export cancelled")}}><FileJson size={13}/> Export diagnostics</button></div><div className="privacy-note"><CheckCircle2/><span><strong>Private by default</strong><small>Diagnostics exclude project names, media paths, captions, and creative content.</small></span></div></>}
      </main>
      <footer><span role="status">{message}</span><code>{status?.runtime} · SDK {status?.sdkVersion}</code></footer>
    </section>
  </div>;
}
function formatBytes(bytes:number){return bytes>=1024**3?(bytes/1024**3).toFixed(1)+" GB":Math.round(bytes/1024**2)+" MB"}
